### ISSUE TITLE
can you release ? composer  has bug  "not find package"

### ISSUE THREAD

**Issue by xjdata** [udokmeci/yii2-beanstalk#10]
can you release ? composer  report  bug  "not find package"

thanks.

**Comment by udokmeci** [comment]
Hi, can you send composer json or how you install the package.
I tired ```composer require "udokmeci/yii2-beanstalk:dev-master"``` and it works

**Comment by xjdata** [comment]
thanks.
this is my  conspose.json

for install  i set  "minimum-stability": "dev",    

```
  "minimum-stability": "dev",
  "require": {
    "yiisoft/yii2": "2.0.6",
... other package
    "udokmeci/yii2-beanstalk" : "dev-master",
... other package
}
```
