### ISSUE TITLE
Limit number of tubes to be watched

### ISSUE THREAD

**Issue by macklus** [udokmeci/yii2-beanstalk#11]
Hi:

Is there any way to listen only in a predefined list of tubes??

Is server has:
- tube1
- tube2
- tube3

somethind like:

public function listenOnlyTubes(){
    return ["tube1","tube2"];
  }

so, this run not try to do works from tube3 tube.

**Comment by macklus** [comment]
I made that change, and test it works.
it was really helpful if you test and add to your code, so i can deploy that on all my servers

Thanks in advance!

[BeanstalkController.php.diff.txt](https://github.com/udokmeci/yii2-beanstalk/files/50530/BeanstalkController.php.diff.txt)

**Comment by udokmeci** [comment]
Hey,
Why do you want it to work only that way for everybody? There are people using it in that way already. You can add those lines to your controller class, just override the getTubes function and add your listenOnlyTubes functions and voila it will work.

**Comment by macklus** [comment]
Hey,
i dont want to work only in that way. If you see attached patch, it only works if function listenOnlyTubes if defined. I dont break current work.

Patch was attached to get "another option" that know we havent (listen only in custom tubes). I deploy it in a few minutes, and send to you, but......

Your solution (override getTubes), seems to be more clear and efficient, I should have realized before :-(
Even that, if you add that info on README, maybe it should be helpfull from others.

Thanks in advance !!!
