### ISSUE TITLE
Use of undefined constant STDOUT - assumed 'STDOUT'

### ISSUE THREAD

**Issue by MustafaVartech** [udokmeci/yii2-beanstalk#18]
I have error :(

Use of undefined constant STDOUT - assumed 'STDOUT'

**Comment by udokmeci** [comment]
Hi,

OK but how it is not defined. Please check [features.commandline.io-streams](http://php.net/manual/en/features.commandline.io-streams.php)

Seems like encoding problem to me. Please try to delete STDOUT and surroundings and re-type.

Hope that helps out.

**Comment by MustafaVartech** [comment]
Thanks man.
