### ISSUE TITLE
multi threading

### ISSUE THREAD

**Issue by udokmeci** [udokmeci/yii2-beanstalk#2]
would be cupcake

**Comment by michaelarnauts** [comment]
You can just start multiple instances of the `./yii worker` and every instance will fetch it's jobs from the queues. You can also use a tool like supervisor (http://supervisord.org/) to manage your processes. You can simply specify the amount of processes supervisor has to keep online, and it will automatically start new processes if one should die.

**Comment by udokmeci** [comment]
Yeah actually I run multiple instances right now. This was an aim to have a playground for multi-threading feature of  PHP. I did not know about the supervisord thank you for sugesstion. Instead I was using ```screen``` to run multiple instances and to check their output. I will give it a try tomorrow. Definitely will be helpful for somebody. Thank you.
