### ISSUE TITLE
Integration test

### ISSUE THREAD

**Issue by rad8329** [udokmeci/yii2-beanstalk#21]
Hi,

Running the unit test, the environment is obviusly `test`, when a job is put and after that is execute, ¿Exists any way to define `YII_ENV` to `test` in the console command? 

*I thought a craft way, sending `YII_ENV` and in the top o action redefine the `db`  component... but it does not convince me

**Comment by udokmeci** [comment]
Hi,

Sorry what is the problem? I did not get it. [there](https://github.com/udokmeci/yii2-beanstalk/blob/master/tests/bootstrap.php#L4)   is a constant defined for phpunit tests. 

Is there some thing you would like to do with actually running code?

**Comment by rad8329** [comment]
Sorry for my bad English.

The issue is when I was going to run the tests, previously started the worker, obviously that worker started with the `dev` environment, and console configurations instance, then working with database development, not test.

Checking for the boostrap code that you've sent, I can see that you must configure controllerMap and worker controller for the test instance, so  in unit tests run the worker action.

jeje I'll see your test code for never to ask silly things.

Thnaks

**Comment by udokmeci** [comment]
No problem. 

But test coverage is not great so maybe you can contribute to test part if you like.

Thanks

21 Mart 2016 17:23:45 GMT+02:00, "Robert Díaz" <notifications@github.com> yazdı:
>Sorry for my bad English.
>
>The issue is when I was going to run the tests, previously started the
>worker, obviously that worker started with the `dev` environment, and
>console configurations instance, then working with database
>development, not test.
>
>Checking for the boostrap code that you've sent, I can see that you
>must configure controllerMap and worker controller for the test
>instance, so  in unit tests run the worker action.
>
>jeje I'll see your test code for never to ask silly things.
>
>Thnaks
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/udokmeci/yii2-beanstalk/issues/21#issuecomment-199337416

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
