### ISSUE TITLE
Database is require while it shouldn't

### ISSUE THREAD

**Issue by michaelarnauts** [udokmeci/yii2-beanstalk#28]
The `beforeAction` method is reconnecting to the database (to fix for dropped connections probably), but we are not using a database on our server for this project.

All database-related commands should be optional since this forces us to use a database just to interface with beanstalkd.

**Comment by udokmeci** [comment]
Hi,
Isn't it optional I had not tried it but it should catch the exception and continue with one line warning. What is the behavior you get?

Thanks,
