### ISSUE TITLE
Possible race condition

### ISSUE THREAD

**Issue by andreasanta** [udokmeci/yii2-beanstalk#35]
Exception 'Pheanstalk\Exception\ServerException' with message 'Job 318940 NOT_FOUND: does not exist or is not reserved by client' in /var/www/social.zone/ybs/vendor/pda/pheanstalk/src/Command/ReleaseCommand.php:64
Stack trace:
#0 /var/www/social.zone/ybs/vendor/pda/pheanstalk/src/Connection.php(145): Pheanstalk\Command\ReleaseCommand->parseResponse('NOT_FOUND', NULL)
#1 /var/www/social.zone/ybs/vendor/pda/pheanstalk/src/Pheanstalk.php(395): Pheanstalk\Connection->dispatchCommand(Object(Pheanstalk\Command\ReleaseCommand))
#2 /var/www/social.zone/ybs/vendor/pda/pheanstalk/src/Pheanstalk.php(269): Pheanstalk\Pheanstalk->_dispatch(Object(Pheanstalk\Command\ReleaseCommand))
#3 [internal function]: Pheanstalk\Pheanstalk->release(Object(Pheanstalk\Job), '1000', 300)
#4 /var/www/social.zone/ybs/vendor/udokmeci/yii2-beanstalk/src/udokmeci/yii2beanstalk/Beanstalk.php(94): call_user_func_array(Array, Array)
#5 /var/www/social.zone/ybs/vendor/udokmeci/yii2-beanstalk/src/udokmeci/yii2beanstalk/BeanstalkController.php(376): udokmeci\yii2beanstalk\Beanstalk->__call('release', Array)
#6 /var/www/social.zone/ybs/vendor/udokmeci/yii2-beanstalk/src/udokmeci/yii2beanstalk/BeanstalkController.php(376): udokmeci\yii2beanstalk\Beanstalk->release(Object(Pheanstalk\Job), '1000', 300)
#7 /var/www/social.zone/ybs/vendor/udokmeci/yii2-beanstalk/src/udokmeci/yii2beanstalk/BeanstalkController.php(318): udokmeci\yii2beanstalk\BeanstalkController->executeJob('actionPre', Object(Pheanstalk\Job))
#8 /var/www/social.zone/ybs/vendor/yiisoft/yii2/base/Controller.php(152): udokmeci\yii2beanstalk\BeanstalkController->beforeAction(Object(yii\base\InlineAction))
#9 /var/www/social.zone/ybs/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('', Array)
#10 /var/www/social.zone/ybs/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('', Array)
#11 /var/www/social.zone/ybs/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('worker', Array)
#12 /var/www/social.zone/ybs/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('worker', Array)
#13 /var/www/social.zone/ybs/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 /var/www/social.zone/ybs/yii(30): yii\base\Application->run()
#15 {main}

**Comment by udokmeci** [comment]
If Job Not found than beanstalk does not have that job. How long does it take to release after reserve. If it is TTR then you need to touch job before TTR like ```Yii::$app->beanstalk->touch($job);```. If this is not the case please inform me about more code. Please check out: [touch method](http://beanstalkc.readthedocs.io/en/latest/reference.html#beanstalkc.Connection.touch)

**Comment by andreasanta** [comment]
Thank you for your reply.

Unfortunately, I cannot touch the job, since it depends on an external HTTP connection that might time out. I just return return self::DELAY after handling the job.

Can you please double check the code and trap the exception at 
beanstalk/src/udokmeci/yii2beanstalk/Beanstalk.php(94)

Thanks!

**Comment by udokmeci** [comment]
Hi,
When creating a job please set a higher ttr that would also be you http request timeout.
Isn't it possible?
I'll close for now. Please re open if you think that is not better?
Thanks
