### ISSUE TITLE
Multiple workers

### ISSUE THREAD

**Issue by StalkAlex** [udokmeci/yii2-beanstalk#40]
What if I want to run several workers, what would be the best implementation?

**Comment by udokmeci** [comment]
I use [screen](https://www.gnu.org/software/screen/manual/screen.html),
So why not?

**Comment by StalkAlex** [comment]
Now we have one controller with all tubes and run one process(basically I followed your documentation), but I thought tube is something that detached from others and tasks will be running parallely among all of them. But it's not. So now if I want to make more workers for one-two tube only, I have to create another controller, refactor current one, then make another command in yii application and run it. But after some time I decide to make changes once again for example, and I need to refactor classes again. Is there more like configuration friendly decision, something that can be setup by configs only? It will be more friendly for deploy process and for scalability.

**Comment by StalkAlex** [comment]
Ok...
