### ISSUE TITLE
Error: Unable to locate message source for category 'udokmeci.beanstalkd'.

### ISSUE THREAD

**Issue by michaelarnauts** [udokmeci/yii2-beanstalk#8]
Since commit b946bac28dca01bf9e7839fafdf2c1417f95d9dd, i18n was added that required additional configuration.

I just did a composer update tot get the fix for #7, but now I get the following message:

```
Error: Unable to locate message source for category 'udokmeci.beanstalkd'.
```

**Comment by udokmeci** [comment]
Hi.
Since I had not get such an error. I did not mind to have such a problem.
I have tested it locally and there was no such error.

Now please do update again.
