### ISSUE TITLE
Exception:  'Job 5 NOT_FOUND: does not exist or is not reserved by client'

### ISSUE THREAD

**Issue by vitaliykoziy** [udokmeci/yii2-beanstalk#9]
Hi.
I have issue:
exception 'Pheanstalk\Exception\ServerException' with message 'Job 5 NOT_FOUND: does not exist or is not reserved by client' in /var/www/site/vendor/pda/pheanstalk/src/Command/ReleaseCommand.php:63

My code executes about 77 s. I think, that is why I have this issue.
What can I do for fix this?
Help please.
Thks.

**Comment by udokmeci** [comment]
Hey, if you have data and done with it just return no-action so it will not try to release a gone job or just cathcth the error and do nothing

> 
> Ugur Dokmeci 
> Tel: +90-532-383 39 44 


19 Haz 2015 tarihinde 01:10 saatinde, vitaliykoziy <notifications@github.com> şunları yazdı:

**Comment by vitaliykoziy** [comment]
I did, as You recommend.
```php
public function actionDoSome($job)
    {
        try {

            //some code
            return self::NO_ACTION;
        } catch (\Exception $exc) {
            return self::DELETE;
        }
    }
```
It is ok. But job running twice. And Job delete after second run, when exception catched.


I resolve my issue by this way

```php
 Yii::$app->beanstalk->putInTube('doSome', $job, $priority, 0, $ttr);
```
where 
```php
$ttr = 600 (s).
```

Thanks, for your help.

**Comment by udokmeci** [comment]
Hi,

You welcome, an alternative approach would be set a timeout for the job when reserving.
checkout https://github.com/pda/pheanstalk/blob/master/src/Pheanstalk.php#L279
public function reserve($timeout = null)

**Comment by githubjeka** [comment]
No way to use `reserve` [because you code is](https://github.com/udokmeci/yii2-beanstalk/blob/4fba459c7c586bf4933a2aca0abddf1dd179e8ac/src/udokmeci/yii2beanstalk/BeanstalkController.php#L307-L310) 
```php
                   $job = $bean->reserve();
                            if (!$job) {
                                continue;
                            }
```
